# Generated by Django 3.0.8 on 2021-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='na@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='genre',
            field=models.CharField(default='MISC', max_length=255),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_not_crawled',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='insta_username',
            field=models.CharField(default='NA', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
