# Generated by Django 3.0.8 on 2021-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210527_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default=None, max_length=255)),
                ('done', models.IntegerField(default=0, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='api_user_id',
            field=models.CharField(default='NA', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='image_url',
            field=models.CharField(default='NA', max_length=255, unique=True),
        ),
    ]
