# Generated by Django 3.0.8 on 2021-05-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('insta_username', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
