# Generated by Django 3.0.8 on 2021-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210528_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='done',
            field=models.IntegerField(default=0),
        ),
    ]
