# Generated by Django 3.0.8 on 2021-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_accounts_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='followers',
            field=models.IntegerField(default=None),
        ),
    ]
